# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48c9618d492392109e77b1a5e519d92790b873d98ea2dc75ae195dede34bf516855905d656761fbf6433acb9a4f5fbc0ca6b8cbd21e3d1ec75f347d889f0a329

test:
  secret_key_base: 0240f82bbca4fa8bd5d425c1d67ae3e6a95e865610cac1d4567b973e31b4814495d23b71b601d0e9e57a65169b91351c8993a5e8954afbf6942787117be12e55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
